name: My Jekyll Website

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections_dir: collections

collections:
    - experience
    - posts
    - drafts
    
# Google Analytics
google_analytics: UA-147164583-1

google_verify: ve2lVCW3f_Z8QELKalmk0LVq3BeBhWQjKlU-0IQYBYI

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
  